# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notify/notify.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'notify/notify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notify/notify.proto\x12\x0f\x66\x65\x65\x64s.notify.v1\"V\n\x07PushReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\"B\n\x08PushResp\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x64\x65livered_ws\x18\x02 \x01(\x08\x12\x14\n\x0c\x64\x65vice_count\x18\x03 \x01(\x05\"J\n\x14ListNotificationsReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\x03\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"^\n\x15ListNotificationsResp\x12\x30\n\x05items\x18\x01 \x03(\x0b\x32!.feeds.notify.v1.NotificationItem\x12\x13\n\x0bnext_cursor\x18\x02 \x01(\x03\"\x7f\n\x10NotificationItem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x0f\n\x07is_read\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"7\n\x0bMarkReadReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0fnotification_id\x18\x02 \x01(\t\"\x1a\n\x0cMarkReadResp\x12\n\n\x02ok\x18\x01 \x01(\x08\"$\n\x11GetUnreadCountReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"#\n\x12GetUnreadCountResp\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32\xd4\x02\n\rNotifyService\x12;\n\x04Push\x12\x18.feeds.notify.v1.PushReq\x1a\x19.feeds.notify.v1.PushResp\x12\x62\n\x11ListNotifications\x12%.feeds.notify.v1.ListNotificationsReq\x1a&.feeds.notify.v1.ListNotificationsResp\x12G\n\x08MarkRead\x12\x1c.feeds.notify.v1.MarkReadReq\x1a\x1d.feeds.notify.v1.MarkReadResp\x12Y\n\x0eGetUnreadCount\x12\".feeds.notify.v1.GetUnreadCountReq\x1a#.feeds.notify.v1.GetUnreadCountRespB0Z.github.com/TheChosenGay/feeds/proto/gen/notifyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notify.notify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/TheChosenGay/feeds/proto/gen/notify'
  _globals['_PUSHREQ']._serialized_start=40
  _globals['_PUSHREQ']._serialized_end=126
  _globals['_PUSHRESP']._serialized_start=128
  _globals['_PUSHRESP']._serialized_end=194
  _globals['_LISTNOTIFICATIONSREQ']._serialized_start=196
  _globals['_LISTNOTIFICATIONSREQ']._serialized_end=270
  _globals['_LISTNOTIFICATIONSRESP']._serialized_start=272
  _globals['_LISTNOTIFICATIONSRESP']._serialized_end=366
  _globals['_NOTIFICATIONITEM']._serialized_start=368
  _globals['_NOTIFICATIONITEM']._serialized_end=495
  _globals['_MARKREADREQ']._serialized_start=497
  _globals['_MARKREADREQ']._serialized_end=552
  _globals['_MARKREADRESP']._serialized_start=554
  _globals['_MARKREADRESP']._serialized_end=580
  _globals['_GETUNREADCOUNTREQ']._serialized_start=582
  _globals['_GETUNREADCOUNTREQ']._serialized_end=618
  _globals['_GETUNREADCOUNTRESP']._serialized_start=620
  _globals['_GETUNREADCOUNTRESP']._serialized_end=655
  _globals['_NOTIFYSERVICE']._serialized_start=658
  _globals['_NOTIFYSERVICE']._serialized_end=998
# @@protoc_insertion_point(module_scope)
