# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from notify import notify_pb2 as notify_dot_notify__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notify/notify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotifyServiceStub:
    """NotifyService 提供通知推送和历史查询功能。
    其他服务通过此接口发送通知，notify 内部通过 comet gRPC 投递到在线用户。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/feeds.notify.v1.NotifyService/Push',
                request_serializer=notify_dot_notify__pb2.PushReq.SerializeToString,
                response_deserializer=notify_dot_notify__pb2.PushResp.FromString,
                _registered_method=True)
        self.ListNotifications = channel.unary_unary(
                '/feeds.notify.v1.NotifyService/ListNotifications',
                request_serializer=notify_dot_notify__pb2.ListNotificationsReq.SerializeToString,
                response_deserializer=notify_dot_notify__pb2.ListNotificationsResp.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/feeds.notify.v1.NotifyService/MarkRead',
                request_serializer=notify_dot_notify__pb2.MarkReadReq.SerializeToString,
                response_deserializer=notify_dot_notify__pb2.MarkReadResp.FromString,
                _registered_method=True)
        self.GetUnreadCount = channel.unary_unary(
                '/feeds.notify.v1.NotifyService/GetUnreadCount',
                request_serializer=notify_dot_notify__pb2.GetUnreadCountReq.SerializeToString,
                response_deserializer=notify_dot_notify__pb2.GetUnreadCountResp.FromString,
                _registered_method=True)


class NotifyServiceServicer:
    """NotifyService 提供通知推送和历史查询功能。
    其他服务通过此接口发送通知，notify 内部通过 comet gRPC 投递到在线用户。
    """

    def Push(self, request, context):
        """Push 推送一条通知。内部会存储到数据库并尝试通过 comet 实时投递。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """ListNotifications 查询用户的通知历史，按时间倒序。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """MarkRead 标记通知为已读。notification_id 为 "all" 时标记全部。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnreadCount(self, request, context):
        """GetUnreadCount 获取未读通知数量（用于红点展示）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=notify_dot_notify__pb2.PushReq.FromString,
                    response_serializer=notify_dot_notify__pb2.PushResp.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=notify_dot_notify__pb2.ListNotificationsReq.FromString,
                    response_serializer=notify_dot_notify__pb2.ListNotificationsResp.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=notify_dot_notify__pb2.MarkReadReq.FromString,
                    response_serializer=notify_dot_notify__pb2.MarkReadResp.SerializeToString,
            ),
            'GetUnreadCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnreadCount,
                    request_deserializer=notify_dot_notify__pb2.GetUnreadCountReq.FromString,
                    response_serializer=notify_dot_notify__pb2.GetUnreadCountResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feeds.notify.v1.NotifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('feeds.notify.v1.NotifyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotifyService:
    """NotifyService 提供通知推送和历史查询功能。
    其他服务通过此接口发送通知，notify 内部通过 comet gRPC 投递到在线用户。
    """

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feeds.notify.v1.NotifyService/Push',
            notify_dot_notify__pb2.PushReq.SerializeToString,
            notify_dot_notify__pb2.PushResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feeds.notify.v1.NotifyService/ListNotifications',
            notify_dot_notify__pb2.ListNotificationsReq.SerializeToString,
            notify_dot_notify__pb2.ListNotificationsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feeds.notify.v1.NotifyService/MarkRead',
            notify_dot_notify__pb2.MarkReadReq.SerializeToString,
            notify_dot_notify__pb2.MarkReadResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnreadCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/feeds.notify.v1.NotifyService/GetUnreadCount',
            notify_dot_notify__pb2.GetUnreadCountReq.SerializeToString,
            notify_dot_notify__pb2.GetUnreadCountResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
